name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Slither Static Analysis
        uses: crytic/slither-action@v0.3.0
        with: 
          solc-version: '0.8.9'
          node-version: 18.x

